<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_event_registration"
 *
 * Auto generated by Extension Builder 2016-12-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News Frontend Event Registration',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Georg Ringer',
    'author_email' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            'news' => '',
            'news_eventfields' => ''
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
